[package]
name = "bedrock-finder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7"
cust = "0.3"

[build-dependencies]
cuda_builder = "0.3"
